services:
  whisper-streamer:
    image: whisper-streamer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARCH=linux/amd64
    container_name: whisper-streamer
    restart: unless-stopped
    ports:
      - 43001:43001
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    entrypoint: ["/bin/bash", "start_whisper_stream.sh"]
    
