services:
  whisper-streamer:
    image: whisper-streamer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisper-streamer
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    entrypoint: ["/bin/bash", "start_whisper_stream.sh"]
    
